# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.14-slim

EXPOSE 8080

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements

WORKDIR /app

COPY requirements.txt .
RUN apt-get -y update \
    && apt-get -y install libpq-dev gcc
    # && python -m pip install -r requirements.txt

COPY ./src/ ./src/
COPY ./static/ ./static/
COPY .env ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["fastapi", "run", "main.py", "--port", "8080"]
